resources:
- ../base

patches:
- target:
    kind: Subscription
    name: health-check-subscription
  patch: |
    - op: replace
      path: /metadata/name
      value: health-check-dev-subscription
    - op: replace
      path: /metadata/labels/app
      value: health-check-dev
    - op: replace
      path: /spec/placement/placementRef/name
      value: health-check-dev-placement
- target:
    kind: Subscription
    name: health-check-secrets-subscription
  patch: |
    - op: replace
      path: /metadata/name
      value: health-check-secrets-dev-subscription
    - op: replace
      path: /metadata/labels/app
      value: health-check-secrets-dev
    - op: replace
      path: /spec/placement/placementRef/name
      value: health-check-secrets-dev-placement
- target: 
    kind: PlacementRule
    name: health-check-placement
  patch: |
    - op: replace
      path: /metadata/name
      value: health-check-dev-placement
    - op: replace
      path: /spec/clusterSelector/matchExpressions/1/values
      value:
        - dev
- target: 
    kind: PlacementRule
    name: health-check-secrets-placement
  patch: |
    - op: replace
      path: /metadata/name
      value: health-check-secrets-dev-placement
    - op: replace
      path: /spec/clusterSelector/matchExpressions/2/values
      value:
        - dev

