---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: health-check
  namespace: canary
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: health-check
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: health-check-secrets
  namespace: canary
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: health-check-secrets




