---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: health-check-placement
  namespace: canary
  annotations: {}
  labels:
    app: health-check
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: health-check-secrets-placement
  namespace: canary
  annotations:
    secretname: "pull-secret"
spec:
  clusterSelector:
    matchExpressions:
    - key: vendor
      operator: In
      values:
      - OpenShift
    - key: local-cluster
      operator: DoesNotExist
