---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: health-check-subscription
  namespace: canary
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: basic
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: health-check
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: git-repos/health-check-channel
  placement:
    placementRef:
      name: health-check-placement
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: health-check-secrets-subscription
  namespace: canary
  labels:
    app: health-check-secrets
spec:
  channel: canary/health-check-secrets-channel
  packageFilter:
    annotations:
      secretname: "pull-secret"
  placement:
    placementRef:
      kind: PlacementRule
      name: health-check-secrets-placement
