apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: health-check-secrets-placement
  namespace: canary
  annotations:
    secretname: "pull-secret"
spec:
  clusterSelector:
    matchExpressions:
    - key: local-cluster
      operator: DoesNotExist
    - key: vendor
      operator: In
      values:
      - OpenShift
    matchLabels:
      environment: REPLACE BY KUSTOMIZE

