---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-secrets
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-secrets-config
        spec:
          remediationAction: enforce
          severity: low
          namespaceSelector:
            include:
              - default
              - test
              - secrets
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: pull-secret
                  namespace: test
                  annotations:
                    app.open-cluster-management.io/deployables: "secret"
                data:
                  username: '{{ fromSecret "secrets" "pull-secret" "username" }}'
                  password: '{{ fromSecret "secrets" "pull-secret" "password" }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-secrets
placementRef:
  name: placement-policy-secrets
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-secrets
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-secrets
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchLabels:
      environment: dev
