apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-secrets
  namespace: test
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-secrets-config
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            include:
              - secrets
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: pull-secret
                  namespace: test
                  annotations:
                    app.open-cluster-management.io/deployables: "secret"
                data:
                  username: {{ fromSecret "secrets" "pull-secret" "username" }}
                  password: {{ fromSecret "secrets" "pull-secret" "password" }}
