apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: health-check-subscription
  namespace: canary
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: secrets
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: health-check
spec:
  channel: git-repos/health-check-channel
  placement:
    placementRef:
      name: health-check-placement
      kind: PlacementRule
