---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: secrets-application
  namespace: secrets
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      app: secrets
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: secrets-subscription
  namespace: secrets
  annotations: {}
  labels:
    app: secrets
spec:
  channel: secrets-channel/secrets
  packageFilter:
    annotations: {}
  placement:
    placementRef:
      name: secrets-placement
      kind: PlacementRule
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: secrets-placement
  namespace: secrets
  annotations: {}
spec:
  clusterSelector:
    matchLabels:
      environment: dev

